import type { GalleryItemPublic } from "@/lib/public-types";

export type GalleryImage = {
  id: string;
  src: string;
  alt: string;
  caption?: string;
  category?: string;
  objectPosition?: string;
  width?: number;
  height?: number;
  title: string;
  albumSlug: string;
  albumTitle: string;
  contributor?: string;
  date?: string;
};

const publicGalleryImages: GalleryImage[] = [
  {
    id: "public-gallery-main-portrait",
    src: "/images/pa-ndambi-main-portrait.png",
    alt: "Portrait of Pa Ndambi Paul Angemba",
    caption: "A formal portrait of Pa Ndambi Paul Angemba.",
    category: "Portraits",
    objectPosition: "center 18%",
    title: "Formal portrait",
    albumSlug: "portraits",
    albumTitle: "Portraits",
    contributor: "Family Archive",
    date: "2026-06-25",
  },
  {
    id: "public-gallery-close-portrait",
    src: "/images/pa-ndambi/pa-ndambi-close-portrait.jpg",
    alt: "Close portrait of Pa Ndambi Paul Angemba",
    caption: "A close portrait remembered by the family.",
    category: "Portraits",
    objectPosition: "center 18%",
    title: "Close portrait",
    albumSlug: "portraits",
    albumTitle: "Portraits",
    contributor: "Family Archive",
    date: "2026-06-25",
  },
  {
    id: "public-gallery-traditional-blue",
    src: "/images/pa-ndambi/pa-ndambi-traditional-blue.jpg",
    alt: "Pa Ndambi Paul Angemba standing in blue attire",
    caption: "A dignified portrait in blue attire.",
    category: "Portraits",
    objectPosition: "center 22%",
    title: "Blue attire portrait",
    albumSlug: "portraits",
    albumTitle: "Portraits",
    contributor: "Family Archive",
    date: "2026-06-25",
  },
  {
    id: "public-gallery-hero-regalia",
    src: "/images/pa-ndambi/hero-pa-ndambi-blue-regalia.jpg",
    alt: "Pa Ndambi Paul Angemba in blue regalia",
    caption: "A treasured portrait in blue regalia.",
    category: "Portraits",
    objectPosition: "center 16%",
    title: "Blue regalia portrait",
    albumSlug: "portraits",
    albumTitle: "Portraits",
    contributor: "Family Archive",
    date: "2026-06-25",
  },
  {
    id: "public-gallery-family345",
    src: "/images/pa-ndambi/family345.jpeg",
    alt: "Family photograph from the Pa Ndambi archive",
    caption: "A family photograph preserved in the memorial archive.",
    category: "Family",
    title: "Family archive photograph",
    albumSlug: "family-memories",
    albumTitle: "Family Memories",
    contributor: "Family Archive",
    date: "2026-06-25",
  },
  {
    id: "public-gallery-scout-memory",
    src: "/images/pa-ndambi/pa-ndambi-scout-memory.jpg",
    alt: "Pa Ndambi Paul Angemba in a Scout memory photograph",
    caption: "A Scout memory preserved by the family.",
    category: "Scouting and Service",
    objectPosition: "center 20%",
    title: "Scout memory",
    albumSlug: "scouting-and-service",
    albumTitle: "Scouting and Service",
    contributor: "Family Archive",
    date: "2026-06-25",
  },
  {
    id: "public-gallery-beach",
    src: "/images/pa-ndambi/pa-ndambi-beach.jpg",
    alt: "Pa Ndambi Paul Angemba by the shore",
    caption: "A family moment by the shore.",
    category: "Family",
    objectPosition: "center 28%",
    title: "Family moment by the shore",
    albumSlug: "family-memories-abroad",
    albumTitle: "Family Memories Abroad",
    contributor: "Family Archive",
    date: "2026-06-25",
  },
  {
    id: "public-gallery-snow",
    src: "/images/pa-ndambi/pa-ndambi-snow.jpg",
    alt: "Pa Ndambi Paul Angemba photographed in a snowy setting",
    caption: "A later-life photograph from family travel.",
    category: "Travel and Later Life",
    objectPosition: "center 30%",
    title: "Snow memory",
    albumSlug: "travel-and-later-life",
    albumTitle: "Travel and Later Life",
    contributor: "Family Archive",
    date: "2026-06-25",
  },
  {
    id: "public-gallery-car-snow",
    src: "/images/pa-ndambi/pa-ndambi-car-snow.jpg",
    alt: "Pa Ndambi Paul Angemba near a car in the snow during family travel",
    caption: "A travel memory from later life.",
    category: "Travel and Later Life",
    objectPosition: "center 34%",
    title: "Travel memory in the snow",
    albumSlug: "travel-and-later-life",
    albumTitle: "Travel and Later Life",
    contributor: "Family Archive",
    date: "2026-06-25",
  },
  {
    id: "public-gallery-olympic-stadium",
    src: "/images/pa-ndambi/pa-ndambi-olympic-stadium.jpg",
    alt: "Pa Ndambi Paul Angemba near an Olympic stadium during travel",
    caption: "A travel photograph from the family archive.",
    category: "Travel and Later Life",
    objectPosition: "center 28%",
    title: "Journey and legacy",
    albumSlug: "travel-and-later-life",
    albumTitle: "Travel and Later Life",
    contributor: "Family Archive",
    date: "2026-06-25",
  },
  {
    id: "public-gallery-airport-profile",
    src: "/images/pa-ndambi/pa-ndambi-airport-profile.jpg",
    alt: "Pa Ndambi Paul Angemba at an airport",
    caption: "A portrait captured during travel.",
    category: "Travel and Later Life",
    objectPosition: "center 24%",
    title: "Airport profile",
    albumSlug: "travel-and-later-life",
    albumTitle: "Travel and Later Life",
    contributor: "Family Archive",
    date: "2026-06-25",
  },
  {
    id: "public-gallery-street",
    src: "/images/pa-ndambi/pa-ndambi-street.jpg",
    alt: "Pa Ndambi Paul Angemba outdoors on a street",
    caption: "An outdoor memory from later life.",
    category: "Travel and Later Life",
    objectPosition: "center 26%",
    title: "Street memory",
    albumSlug: "travel-and-later-life",
    albumTitle: "Travel and Later Life",
    contributor: "Family Archive",
    date: "2026-06-25",
  },
];

export function getPublicGalleryManifest(): GalleryItemPublic[] {
  return publicGalleryImages.map((image) => ({
    id: image.id,
    kind: "image",
    title: image.title,
    caption: image.caption || image.title,
    altText: image.alt,
    contributor: image.contributor || "Family Archive",
    date: image.date || "2026-06-25",
    posterUrl: image.src,
    publicUrl: image.src,
    albumTitle: image.albumTitle,
  }));
}

export const publicGalleryAudit = [
  { path: "public/icons/apple-touch-icon.png", status: "excluded as UI asset" },
  { path: "public/icons/icon-192.png", status: "excluded as UI asset" },
  { path: "public/icons/icon-512.png", status: "excluded as UI asset" },
  { path: "public/images/pa-ndambi-logo-circle.png", status: "excluded as UI asset" },
  { path: "public/images/pa-ndambi-logo-square.png", status: "excluded as UI asset" },
  { path: "public/images/pa-ndambi-main-portrait.png", status: "included" },
  { path: "public/images/pa-ndambi/family345.jpeg", status: "included" },
  { path: "public/images/pa-ndambi/hero-pa-ndambi-blue-regalia.jpg", status: "included" },
  { path: "public/images/pa-ndambi/pa-ndambi-airport-profile.jpg", status: "included" },
  { path: "public/images/pa-ndambi/pa-ndambi-beach.jpg", status: "included" },
  { path: "public/images/pa-ndambi/pa-ndambi-blue-cutout.png", status: "excluded as UI asset" },
  { path: "public/images/pa-ndambi/pa-ndambi-car-snow.jpg", status: "included" },
  { path: "public/images/pa-ndambi/pa-ndambi-close-portrait.jpg", status: "included" },
  { path: "public/images/pa-ndambi/pa-ndambi-olympic-stadium.jpg", status: "included" },
  { path: "public/images/pa-ndambi/pa-ndambi-scout-cutout.png", status: "excluded as UI asset" },
  { path: "public/images/pa-ndambi/pa-ndambi-scout-memory.jpg", status: "included" },
  { path: "public/images/pa-ndambi/pa-ndambi-snow.jpg", status: "included" },
  { path: "public/images/pa-ndambi/pa-ndambi-street.jpg", status: "included" },
  { path: "public/images/pa-ndambi/pa-ndambi-traditional-blue.jpg", status: "included" },
] as const;
